# encoding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

drink_it = [
  {name: "The Albion Rooms", 
     url: "http://thealbionrooms.com/index.php/our-vision/",
     address: "33 Nicholas Street, Ottawa, ON, K1N9M7",
     phone_number: "613-760-4771",
     walking_time_in_minutes: 7,
     tags: ["Eat it", "Bar", "Restaurant"],
     tagline: "Their constitution: Food, drink and good company."},

  {name: "Barrymore's Music Hall", 
   url: "http://www.barrymores.on.ca/",
   address: "323 Bank Street, Ottawa, ON, K2P 1X9",
   phone_number: "613-565-9999",
   walking_time_in_minutes: 30,
   tags: ["Drink It", "Club", "Indie", "Mowtown", "90's night", "Theme night", "Dancing"],
   tagline: "One of Ottawa's biggest nightclubs, that features 80s & 90s themed nights."},

  {name: "Junxion", 
   url: "http://www.thejunxionottawa.com/",
   address: "15 George Street, Ottawa, ON, K1N 1K2",
   phone_number: "613-241-2868",
   walking_time_in_minutes: 5,
   tags: ["Drink It", "Club", "Dancing", "Top 40", "House", "Live Music"],
   tagline: "Great bar in the Market that's open 5 days a week!"},

  {name: "Zaphods", 
   url: "http://zaphods.ca/",
   address: "27 York Street, Ottawa, ON, K1S 1E2",
   phone_number: "613-562-1010",
   walking_time_in_minutes: 3,
   tags: ["Drink It", "Club", "Indie", "Dance", "Live Music"],
   tagline: "Zaphods welcomes everyone and anyone to their grundge club."},   
   
  {name: "Mercury Lounge", 
   url: "http://www.mercurylounge.com/",
   address: "56 Byward Market Square, Ottawa, ON,",
   phone_number: "613-789-5324",
   walking_time_in_minutes: 4,
   tags: ["Drink It", "Club", "Top 40", "LGBTQ Nights", "Soul"],
   tagline: "Enjoy a night out in this twenty-first century sould club."},

  {name: "Hooleys", 
   url: "http://www.hooleyspub.com/",
   address: "292 Elgin Street, Ottawa, ON, K2P 1M3,",
   phone_number: "613-231-3888",
   walking_time_in_minutes: 15,
   tags: ["Drink It", "Club", "Dance", "Theme Nights", "Top 40"],
   tagline: "This pub turns into a club after 11. Get ready to dance!"},

   {name: "The Senate Sports Tavern & Eatery", 
     url: "http://www.thesenate.ca/",
     address: "33 Clarence Street, Ottawa, ON, K1N5M4",
     phone_number: "613-695-5523",
     walking_time_in_minutes: 5,
     tags: ["Bar", "Sports bar", "eat it", "Patio"],
     description: "Pub fare for the sports fans."},

   {name: "Chez Lucien", 
     url: "http://www.urbanspoon.com/r/250/1346728/restaurant/ByWard-Market-Lower-Town/Chez-Lucien-Ottawa",
     address: "137 Murray Street, Ottawa, ON, K1N5M7",
     phone_number: "613-241-3533",
     walking_time_in_minutes: 4,
     tags: ["eat it", "Intimate", "Bar"],
     description: "The Chez Lucien burger will change your life."},

   {name: "Sir John A Pub", 
     url: "http://www.sirjohna.ca/",
     address: "284 Elgin Street, Ottawa, ON, K2P1M3",
     phone_number: "613-695-5523",
     walking_time_in_minutes: 23,
     tags: ["Bar", "Pub", "eat it", "Patio"],
     description: "Largest selection of craft beer in Centretown."},

   {name: "The Fox & Feather Pub and Grill", 
     url: "http://www.foxandfeather.ca/",
     address: "283 Elgin Street, Ottawa, ON, K2P0L4",
     phone_number: "613-233-2219",
     walking_time_in_minutes: 23,
     tags: ["Bar", "Pub", "eat it", "Patio", "Rooftop Patio"],
     description: "A three-level pub in a more than 100-year-old heritage building."},

   {name: "Heart & Crown", 
     url: "http://www.heartandcrown.ca/",
     address: "67 Clarence Street, Ottawa, ON, K1N5P5",
     phone_number: "613-562-0674",
     walking_time_in_minutes: 4,
     tags: ["eat it", "Bar", "Pub", "Patio", "Irish", "Dancing", "Live Music"],
     description: "You may get lost in this maze of Irish Pubs, but with the live music and bars aplenty, you won't mind."},

   {name: "The Honest Lawyer", 
     url: "http://www.honestlawyer.com/",
     address: "141 George Street, Ottawa, ON, K1N7G1",
     phone_number: "613-562-2262",
     walking_time_in_minutes: 1,
     tags: ["Bar", "Pub", "eat it", "Patio", "Games", "Dancing"],
     description: "Go for a pint and stay for some arcade games."},

   {name: "Pub Italia", 
     url: "http://www.pubitalia.ca/",
     address: "434 1/2 Preston Street, Ottawa, ON, K1S4N4",
     phone_number: "613-232-2326",
     walking_time_in_minutes: 58,
     tags: ["Bar", "Pub", "eat it", "Patio", "Beer Bible"],
     description: "If beer was a religion, this would be your place of worship."},

   {name: "Aulde Dubliner & Pour House", 
     url: "http://www.heartandcrown.ca/dubliner.aspx",
     address: "62 William Street, Ottawa, ON, K1N7A3",
     phone_number: "613-241-0066",
     walking_time_in_minutes: 5,
     tags: ["Bar", "Pub", "eat it", "Patio", "Irish"],
     description: "As Irish a pub as you can get."},

   {name: "Lieutenant's Pump", 
     url: "http://lieutenantspump.ca/",
     address: "361 Elgin Street, Ottawa, ON, K2P1M9",
     phone_number: "613-238-2949",
     walking_time_in_minutes: 26,
     tags: ["Bar", "Pub", "british", "eat it", "Patio", "Brunch"],
     description: "A British pub with tons of local and regional beers."},  

   {name: "The Moonroom", 
     url: "http://www.urbanspoon.com/r/250/1435239/restaurant/Little-Italy/The-Moonroom-Ottawa",
     address: "442 Preston Street, Ottawa, ON, K1S4N6",
     phone_number: "613-231-2525",
     walking_time_in_minutes: 59,
     tags: ["Bar", "Intimate"],
     description: "Unique cocktails and munchies. Try their signature caesar!"},

   {name: "Hooley's", 
     url: "http://www.hooleyspub.com/",
     address: "292 Elgin Street, Ottawa, ON, K2P1M3",
     phone_number: "613-231-3888",
     walking_time_in_minutes: 24,
     tags: ["Bar", "Pub", "Dancing", "Patio"],
     description: "Sneak downstairs to hear some live comedy."}, 

   {name: "Clock Tower Brew Pub", 
     url: "http://clocktower.ca/",
     address: "89 Clarence Street, Ottawa, ON, K1N5P5",
     phone_number: "613-241-8783",
     walking_time_in_minutes: 4,
     tags: ["Bar", "Pub", "Patio"],
     description: "Delicious seasonal brews."}, 

   {name: "Real Sports Bar & Grill", 
     url: "http://realsports.ca/BarAndGrill/Ottawa/",
     address: "90 George Street, Ottawa, ON, K1N7G1",
     phone_number: "613-680-7325",
     walking_time_in_minutes: 4,
     tags: ["Bar", "Sports Bar"],
     description: "Watch your fave sport on one of their 100 HD TVs."}
]

do_it = [
 {name: "Parliament Hill", 
   url: "http://www.parl.gc.ca/Visitors/index-e.asp",
   address: "111 Wellington Street, Ottawa, ON, K1A0A4",
   phone_number: "613-992-4793",
   walking_time_in_minutes: 17,
   tags: ["Tourist Attraction", "Guided Tour", "Walking"],
   description: "Even if you aren’t passionate about politics, you can’t deny the Hill’s beautiful architecture. Take a free guided tour of Centre Block, attend Question Period and explore the Peace Tower. Once dusk hits, stay for the Mosaika light show which runs during the summer. Bring a blanket!"},

 {name: "Haunted Walk", 
   url: "http://www.hauntedwalk.com/ottawatours.php",
   address: "46 Sparks Street, Ottawa, K1P5A5",
   phone_number: "613-232-0344",
   walking_time_in_minutes: 15,
   tags: ["Tourist Attraction", "Guided Tour", "Walking", "Scary"],
   description: "Whether you love horror movies or hate hauntings, channel your inner masochist and sign up for one of Ottawa’s Haunted Walks. Take a lantern-lit journey through Ottawa’s ghastly past. One tour leads you to the former jailhouse gallows; another includes pub pit stops to drink your fears away."},  

 {name: "Rideau Canal", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/rideau-canal-skateway",
   address: "1 Rideau Street, Ottawa, ON, K1N8S7",
   phone_number: "613-239-5000",
   walking_time_in_minutes: 10,
   tags: ["Tourist Attraction", "Skating", "Biking", "Walking"],
   description: "Stroll, bike or rollerblade down this historic, 200-kilometre long waterway. In the winter, lace up your skates and tackle the world’s longest skating rink – 7.8 kilometres long. Take a hot chocolate break while warming your toes on a fire pit along the frozen river."}, 

 {name: "BeaverTails", 
   url: "http://www.beavertailsinc.com/",
   address: "69 George Street, Ottawa, ON, K1N7G1",
   phone_number: "613-241-1230",
   walking_time_in_minutes: 4,
   tags: ["Tourist Attraction", "Food"],
   description: "WTF’s a BeaverTail and why would you want to eat it? Don’t worry – it’s not a REAL beaver’s tail. It’s a fried pastry stretched to look like one, topped with all kinds of sweet and savoury treats. Our recommendation? The Killaloe Sunrise, loaded with sugar, cinnamon and lemon."}, 

 {name: "Bluesfest", 
   url: "http://ottawabluesfest.ca/",
   address: "1 Vimy Place, Ottawa, ON, K1A0M8",
   phone_number: "613-247-1188",
   walking_time_in_minutes: 39,
   tags: ["Tourist Attraction", "Music Festival"],
   description: "Every July, dozens of class acts head to Canada’s capital city to perform at Lebreton Flats. Despite its namesake, Bluesfest features all kinds of musical genres including pop, folk and electronica. Previous performers have included B.B. King, Rush, Snoop Dogg (pardon us, Snoop Lion) and deadmau5."}, 

 {name: "Rideau Centre", 
   url: "http://www.rideaucentre.com/en/Pages/default.aspx",
   address: "50 Rideau Street, Ottawa, ON, K1N9J7",
   phone_number: "613-236-6565",
   walking_time_in_minutes: 8,
   tags: ["Tourist Attraction", "Shopping Mall"],
   description: "More than 180 shops and services make up Ottawa’s largest high-end shopping mall. Retailers include Zara, Sephora, and the Apple Store. It’s a good spot to get your department store fix – but don’t forget to take a gander at the amazing boutiques in the ByWard Market!"}, 

 {name: "Canadian War Museum", 
   url: "http://realsports.ca/BarAndGrill/Ottawa/",
   address: "1 Vimy Place, Ottawa, ON, K1A0M8",
   phone_number: "819-776-7000",
   walking_time_in_minutes: 39,
   tags: ["Tourist Attraction", "Museum"],
   description: "Offering a glimpse into Canada’s military past and present, the national war museum features more than 13,000 artifacts in numerous interactive exhibits. The museum was entirely rebuilt in 2005, and the building’s architecture alone makes it worth the visit. "}, 

 {name: "Museum of Nature", 
   url: "http://realsports.ca/BarAndGrill/Ottawa/",
   address: "240 McLeod Street, Ottawa, ON, K2P2R1",
   phone_number: "613-566-4700",
   walking_time_in_minutes: 30,
   tags: ["Tourist Attraction", "Museum"],
   description: "Dinosaurs and spiders and blue whales, oh my! The castle housing Canada’s Museum of Nature features more than 10 million artifacts – including a 20 foot long blue whale skeleton. Terrified of tarantulas? Stay away from the Animalium, which features all kinds of creepy crawlers."}, 
 {name: "Canadian Museum of History", 
   url: "http://www.civilization.ca/home",
   address: "100 Rue Laurier, Gatineau, QC, K1A0M8",
   phone_number: "819-776-7000",
   walking_time_in_minutes: 25,
   tags: ["Tourist Attraction", "Museum"],
   description: "This national museum (formerly called the Museum of Civilization) celebrates the 20,000 year history and cultural diversity of humans, with a focus on Canadian people. The museum’s roots stretch back to 1856, making it one of North America’s oldest cultural institutions."}, 

 {name: "Lafayette House", 
   url: "http://www.thelaff.ca/",
   address: "42 York Street, Ottawa, ON, K1N5S6",
   phone_number: "613-241-4747",
   walking_time_in_minutes: 4,
   tags: ["Bar", "Pub", "Tourist Attraction"],
   description: "Ottawa’s oldest bar is an attraction in and of itself. Founded in 1849 as Grant’s Hotel, it made the name switch in 1936. Now, it’s known lovingly as The Laff – our dirty bar of choice. Don’t forget to ask the bartender about the secret tunnel underground…"}, 

 {name: "Gatineau Park", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/gatineau-park",
   address: "33 Scott Road, Old Chelsea, QC, J9B1R5",
   phone_number: "819-827-2020",
   walking_time_in_minutes: 196,
   tags: ["Tourist Attraction", "Nature", "Walking", "Biking"],
   description: "Experience Gatineau’s rolling hills and gorgeous landscapes over 361 square kilometres of natural wilderness. Go for a bike ride, hike on a trail and pack a picnic. In the wintertime, go skiing or snowshoeing. Admission is free!"}, 

 {name: "Mackenzie King Estate", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/mackenzie-king-estate/visitor-information",
   address: "Mackenzie King Road, Aylmer, QC, J9J3S4",
   phone_number: "613-827-2020",
   walking_time_in_minutes: 214,
   tags: ["Tourist Attraction", "Museum", "Nature", "Walking"],
   description: "Bet you’re dying to learn more about Canada’s 10th prime minister William Lyon Mackenzie King. No? Regardless, stop by his former estate for the beautiful gardens, ruins and cottages that King lived in for almost 50 years before dying there and leaving the estate as a public park."}, 

 {name: "Hog's Back Falls", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/parks-paths/hog%E2%80%99s-back-park",
   address: "Hog's Back Road, Ottawa, ON, K1A0M2",
   phone_number: "613-239-5000",
   walking_time_in_minutes: 105,
   tags: ["Tourist Attraction", "Nature", "Walking"],
   description: "If water is therapeutic, waterfalls are a full-on therapy session. You can find the falls inside Hog’s Back Park on the Rideau River. There’s a concession stand for snacks, which is licensed to sell alcohol. For real. Go get yourself a (legal) beer in a (beautiful) public place."}, 

 {name: "Dow's Lake", 
   url: "http://www.dowslake.com/",
   address: "1001 Queen Elizabeth Drive, Ottawa, ON, K1S5K7",
   phone_number: "613-232-1001",
   walking_time_in_minutes: 60,
   tags: ["Tourist Attraction", "Restaurant", "Paddleboating", "Canoeing", "Skating"],
   description: "Watch your fave sport on one of their 100 HD TVs."},

 {name: "Brewer Park Farmer's Market", 
   url: "http://ottawafarmersmarket.ca/brewer-park-ottawa/",
   address: "Sloan Avenue, Ottawa, ON, K1S5S1",
   phone_number: "613-218-7502",
   walking_time_in_minutes: 71,
   tags: ["Tourist Attraction", "Farmer's Market"],
   description: "More than 100 vendors sell local produce, preserves, cheeses and desserts at this weekly summer market. There are tons of picnic tables in case you can’t wait to get home to test your treats! Open between May and November on Sundays between 8 a.m. and 3 p.m."},  

 {name: "Confederation Park", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/parks-paths/confederation-park",
   address: "Confederation Park, Ottawa, ON, K1P5J2",
   phone_number: "613-239-5000",
   walking_time_in_minutes: 17,
   tags: ["Tourist Attraction", "Park", "Walking"],
   description: "There’s always something going on in Confederation Park – Canada Day festivities, Winterlude activities, the Ottawa International Jazz Festival, street performers or just passersby that are reeeally fun to people-watch. You’ll encounter many memorials, including a fountain for Colonel By."}, 

 {name: "Nepean Point", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/parks-paths/nepean-point-astrolabe-theatre",
   address: "Alexandra Bridge, Ottawa, ON",
   phone_number: "613-239-5000",
   walking_time_in_minutes: 13,
   tags: ["Lookout", "Tourist Attraction", "Nature"],
   description: "One of the best views of the city. Hang out with French explorer Samuel de Champlain – atop the vista sits a statue of him holding his famous astrolabe (read: old-school navigational tool) next to an amphitheatre called Astrolabe Theatre. A great place to escape the city noise."}, 

 {name: "Major's Hill Park", 
   url: "http://www.ncc-ccn.gc.ca/places-to-visit/parks-paths/majors-hill-park",
   address: "Mackenzie Avenue, Ottawa, ON, K1N9J6",
   phone_number: "613-237-5150",
   walking_time_in_minutes: 9,
   tags: ["Park", "Tourist Attraction", "Nature", "Walking"],
   description: "Need a quick retreat from the city streets? Major’s Hill Park was Ottawa’s first green space and is full of enormous trees, ahh-worthy gardens and so much open space. It’s a short walk from Shopify’s headquarters and a great place to play frisbee or enjoy a picnic lunch."}, 

 {name: "Sparks Street", 
   url: "http://www.sparksstreetmall.com/",
   address: "35 O'Connor Street, Unit 300, Ottawa, ON, K1P0A1",
   phone_number: "613-230-0984",
   walking_time_in_minutes: 21,
   tags: ["Shopping", "Tourist Attraction", "Walking"],
   description: "There are all kinds of neat events that tuck themselves within this outdoor mall, including Ribfest, International Buskerfest and Winterbrewed, a wintertime beer festival. Sparks Street was founded in the early 1800s and has become a hub for shopping, dining and special events."}, 

 {name: "ByWard Market", 
   url: "http://www.byward-market.com/",
   address: "55 ByWard Market Square, Ottawa, ON, K1N9C3",
   phone_number: "613-244-4410",
   walking_time_in_minutes: 0,
   tags: ["Tourist Attraction", "Shopping", "Eating", "Walking"],
   description: "The greatest place to eat, work and play. Think we’re biased? The Market is one of Canada’s oldest and largest public markets, with eateries, boutiques and a culture so thriving it’s tangible. There are even cobblestone streets if you’re curious enough to find them. Go explore."},

 {name: "The National Arts Centre", 
   url: "http://nac-cna.ca/",
   address: "53 Elgin Street, Ottawa, ON, K1P5W1",
   phone_number: "613-947-7000",
   walking_time_in_minutes: 14,
   tags: ["Tourist Attraction", "Theatre", "Entertainment"],
   description: "See what sort of musical or theatrical performances are going on while you're here."}
]

eat_it = [
  {name: "Manx", 
   url: "http://manxpub.com",
   address: "370 Elgin Street, Ottawa, ON, K2P1M9",
   phone_number: "613-231-2070",
   walking_time_in_minutes: 25,
   tags: ["eat it", "Brunch", "eat it", "International", "Gluten free friendly"],
   description: "A swanky, dimly lit, tiny piece of Heaven on Elgin.",
   price_range: 2},

   {name: "Black Thorn", 
   url: "http://www.theblackthorn.ca",
   address: "15 Clarence St, Ottawa, ON",
   phone_number: "(613) 241-0712",
   walking_time_in_minutes: 10,
   tags: ["eat it", "Brunch", "eat it", "International", "patio", "pizza", "Gluten free friendly"],
   description: "Gourmet pizza and courtyard patio.",
   price_range: 3},

   {name: "Vittoria Trattoria", 
   url: "http://www.vittoriatrattoria.com",
   address: "35 William Street, Ottawa, ON K1N6Z9",
   phone_number: "(613) 789-8959",
   walking_time_in_minutes: 5,
   tags: ["eat it", "Italian", "BYOB","Gluten free friendly"],
   description: "Antipasti. That's all you need to know.",
   price_range: 3},

   {name: "Must", 
   url: "http://www.mustwinebar.ca",
   address: "41 William St, Ottawa, ON",
   phone_number: "(613) 680-3107",
   walking_time_in_minutes: 5,
   tags: ["eat it", "Wine Bar", "Fine Dine", "Tapas"],
   description: "You must visit this wine bar.",
   price_range: 3},

   {name: "Ahora", 
   url: "http://www.ahora.ca",
   address: "307 Dalhousie Street, Ottawa, ON K1N8Y3",
   phone_number: "(613) 562-2081",
   walking_time_in_minutes: 5,
   tags: ["eat it", "Mexican"],
   description: "Best Mexican in town.",
   price_range: 2},

   {name: "Play Food & Wine", 
   url: "http://www.playfood.ca",
   address: "1 York St,Ottawa, ON K1N6Z5",
   phone_number: "(613) 667-9207",
   walking_time_in_minutes: 10,
   tags: ["eat it", "Wine Bar", "Fine Dine", "Tapas", "BYOB", "Gluten free friendly"],
   description: "A playful fine-dining experience.",
   price_range: 3},

   {name: "Social", 
   url: "http://www.social.ca",
   address: "537 Sussex Dr, Ottawa, ON K1N5S6",
   phone_number: "(613) 789-7355",
   walking_time_in_minutes: 10,
   tags: ["eat it", "Fine Dine", "International", "Gluten free friendly", "vegan friendly"],
   description: "Come for dinner and stay for some drinks.",
   price_range: 4},

   {name: "Murray Street", 
   url: "http://murraystreet.ca",
   address: "110 Murray St, Ottawa, ON K1N5M7",
   phone_number: "(613) 562-7244",
   walking_time_in_minutes: 10,
   tags: ["eat it", "Patio", "International", "Gluten free friendly"],
   description: "For the meat lovers!",
   price_range: 3},

   {name: "Navarra", 
   url: "http://www.urbanspoon.com/r/250/1346729/restaurant/ByWard-Market-Lower-Town/Navarra-Ottawa",
   address: "370 Elgin Street, Ottawa, ON, K2P1M9",
   phone_number: "613-231-2070",
   walking_time_in_minutes: 15,
   tags: ["eat it", "Mexican", "Tapas", "International", "Gluten free friendly"],
   description: "This place believes in sustainable agriculture and slow food",
   price_range: 3},

   {name: "Cornerstone Bar and Grill", 
   url: "http://cornerstonebarandgrill.ca",
   address: "92 Clarence St, Ottawa, ON K1N7B5",
   phone_number: "(613) 241-6835",
   walking_time_in_minutes: 10,
   tags: ["eat it", "International", "Burgers", "eat it", "Gluten free friendly"],
   description: "Good food, great patio!",
   price_range: 2},

   {name: "The 3 Brewers", 
   url: "http://www.les3brasseurs.ca/eng/ottawa_sparks.php",
   address: "240 Sparks Street, Ottawa, ON K1P6C9",
   phone_number: "(613) 380-8140",
   walking_time_in_minutes: 20,
   tags: ["eat it", "eat it", "International"],
   description: "See the beer you're drinking being brewed on the spot.",
   price_range: 2},

   {name: "Taylor's Genuine Food and Wine Bar", 
   url: "http://www.taylorsgenuine.ca",
   address: "1091 Bank St, Ottawa, ON K1S0R4",
   phone_number: "(613) 730-5672",
   walking_time_in_minutes: 60,
   tags: ["eat it", "Patio", "Fine Dine", "International", "Gluten free friendly"],
   description: "Lots of gluten-free options.",
   price_range: 4},

   {name: "Chez Edgar", 
   url: "http://chezedgar.ca",
   address: "60, rue Bégin, Gatineau, Qc, J9A 1C8",
   phone_number: "819-205-1110",
   walking_time_in_minutes: 60,
   tags: ["eat it", "Bakery", "Pastries", "Coffee", "brunch"],
   description: "Amazing brunch and pastries with an intimate feel.",
   price_range: 2},

   {name: "Planet Coffee", 
   url: "https://www.facebook.com/pages/Planet-Coffee/137334522978801",
   address: "24 York Street, Ottawa, ON K1N1K2",
   phone_number: "(613) 789-6261",
   walking_time_in_minutes: 10,
   tags: ["Bakery", "Pastries", "Coffee", "Dessert"],
   description: "Delish coffee shop tucked away in the ByWard Market.",
   price_range: 1},

    {name: "Peter Devine's", 
   url: "http://www.heartandcrown.ca/byward.aspx",
   address: "73 Clarence Street, Ottawa, ON K1N5P5",
   phone_number: "(613) 562-0674",
   walking_time_in_minutes: 5,
   tags: ["eat it", "Irish", "eat it", "Patio"],
   description: "A quiet and cozy Irish pub.",
   price_range: 2},

    {name: "Castle Shawarma ", 
   url: "http://www.urbanspoon.com/r/250/1441369/restaurant/ByWard-Market-Lower-Town/Castle-Shawarma-Ottawa",
   address: "178 Rideau St, Ottawa, ON",
   phone_number: "(613) 789-0009",
   walking_time_in_minutes: 5,
   tags: ["eat it", "Shwarma", "Middle Eastern", "Subs", "fast-food"],
   description: "Perfect late-night food. Watch out for the garlic breath.",
   price_range: 1},

   {name: "Le Boulanger Francais", 
   url: "http://www.bennysbistro.ca/bakery/", 
   address: "119 Murray Street, Ottawa, Canada", 
   phone_number: "613-789-7941", 
   walking_time_in_minutes: 5, 
   tags: ["eat it", "french", "Brunch", "bakery"],
   description: "Delectable and unique brunch steps away from amazing pastries",
   price_range: 2},

  {name: "Hintonburger",
   url: "http://hintonburger.ca/",
   address: "1096 Wellington Street West, Ottawa, Canada",
   phone_number: "613-724-4676",
   walking_time_in_minutes: 60,
   tags: ["eat it", "hamburgers","fast-food"],
   description: "best hamburgers in town",
   price_range: 1},

  {name: "8 Locks’ Flat Canal Bisto",
   url: "http://8locksflat.com/",
   address: "Corktown Bridge, Ottawa, Canada",
   walking_time_in_minutes: 15,
   tags: ["eat it", "patio", "international"],
   description: "Great view, live music, and fantastic food!",
   price_range: 2},

  {name: "El Camino",
   url: "https://www.facebook.com/eatelcamino",
   address: "380 Elgin Street, Ottawa, Ontario",
   walking_time_in_minutes: 30,
   tags: ["eat it", "drink it", "tacos", "Mexican", "Thai"],
   description: "Fantastic fusion tacos and snacks!",
   price_range: 2},

  {name: "Bowich",
   url: "http://www.bowich.ca/",
   address: "155 Bank Street, Ottawa, Canada",
   walking_time_in_minutes: 25,
   tags: ["eat it", "lunch", "brunch", "lunch", "sandwiches"],
   description: "Great place to grab lunch.",
   price_range: 1},

  {name: "Jak’s Kitchen",
   url: "http://jakskitchen.com/",
   address: "479 Bronson Ave, Ottawa, Canada",
   walking_time_in_minutes: 45,
   tags: ["eat it", "brunch","international"],
   description:"Great food from bruch to dinner",
   price_range: 3},

  {name: "Corazón De Maíz", 
   url: "http://www.urbanspoon.com/r/250/1675482/restaurant/ByWard-Market-Lower-Town/Corazon-De-Maiz-Ottawa",
   address: "55 Byward Market Square, Ottawa, Canada",
   phone_number: "(613) 244-1661",
   walking_time_in_minutes: 5,
   tags: ["eat it"]},

  {name: "Chez Lucien",
   url: "http://www.urbanspoon.com/r/250/1346728/restaurant/ByWard-Market-Lower-Town/Chez-Lucien-Ottawa",
   address: "137 Murray Street, Ottawa, Canada",
   phone_number: "(613) 241-3533",
   walking_time_in_minutes: 5,
   tags: ["eat it", "drink it"],
   description:"The Chez Lucien burger will change your life.",
   price_range: 2},

  {name: "Genji Sushi",
   url: "http://www.genji.ca/main4.html/",
   address: "175 Lisgar Street, Ottawa, Canada",
   phone_number: "613-236-2880",
   walking_time_in_minutes: 20,
   tags: ["eat it", "japanese"],
   description: "Best sushi in town",
   price_range: 2},

  {name: "Supply and Demand – Foods and Raw Bar",
   url: "http://www.supplyanddemandfoods.ca/",
   address: "1335 Wellington St W, Ottawa, ON, Canada", 
   phone_number: "(613) 680-2949",
   walking_time_in_minutes: 60,
   tags: ["eat it", "raw", "seafood", "Gluten free friendly"],
   description:"great fresh food",
   price_range: 3 },

  {name: "Town", 
   url: "http://www.townlovesyou.ca/",
   address: "296 Elgin St, Ottawa, ON, Canada",
   phone_number: "(613) 695-8696",
   walking_time_in_minutes: 25,
   tags: ["eat it", "drink it", "Gluten free friendly", "vegan friendly", "International"],
   description:"A restaurant that feels like home.",
   price_range:3},
   
  {name: "Heart and Crown", 
   url: "http://www.heartandcrown.ca/byward.aspx",
   address: "67 Clarence Street, Ottawa, ON, K1N 5P5,",
   phone_number: "613-562-0674",
   walking_time_in_minutes: 4,
   tags: ["Drink It", "Club", "Pub", "Live Music", "Top 40"],
   tagline: "If you love live music and an Irish pub feel, then this is your place! "},

  {name: "Smoque Shack", 
  url: "http://www.smoqueshack.com/",
  address: "129 York Street, Ottawa, ON K1N 7J3,",
  phone_number: "613-789-4245",
  walking_time_in_minutes: 2,
  tags: ["Eat It", "Southern Soul Food", "BBQ"],
  description: "Ultimate Comfort Food!",
  price_range: 3},

  {name: "Hooch Bourbon House", 
  url: "http://hoochbourbon.ca/",
  address: "180 Rideau Street, Ottawa, ON K1N 9N9,",
  phone_number: "613-789-1821",
  walking_time_in_minutes: 5,
  tags: ["Eat It", "drink it", "Southern Soul Food", "Seafood"],
  description: "From chicken and waffles to duck carpacio, a unique and lip smacking experience.",
  price_range: 3},

  {name: "Two Six {Ate}", 
  url: "http://twosixate.com/",
  address: "268 Preston St, Ottawa, ON, K1R 7R3,",
  phone_number: "613-695-8200",
  walking_time_in_minutes: 52,
  tags: ["Eat It", "Italian", "Gastro Pub", "Wine Bar",],
  description: "Tasty snack foods made with local produce.",
  price_range: 2},

  {name: "Smokes Poutinerie", 
  url: "http://smokespoutinerie.com/",
  address: "407 Dalhousie Street, Ottawa, ON, K1RN 9J9,",
  phone_number: "613-789-2873",
  walking_time_in_minutes: 5,
  tags: ["Eat It", "Fast Food", "Late Night"],
  description: "Order the classic or the class with many twists. An Ottawa favorite!",
  price_range: 1},

  {name: "La Bottega", 
  url: "http://www.labottega.ca/",
  address: "64 George Street, Ottawa, ON,",
  phone_number: "613-789-7575",
  walking_time_in_minutes: 5,
  tags: ["Eat It", "Italian", "Fast Food"],
  description: "Build your own Italian experience!",
  price_range: 1},

  {name: "The Works", 
  url: "http://www.worksburger.com/",
  address: "363 St. Laurent Boulevard, Ottawa, ON, K1L 8A6",
  phone_number: "613-748-0406",
  walking_time_in_minutes: 55,
  tags: ["Eat It", "Burgers"],
  description: "Mac and cheese on your burger? No problem! Pulled pork on there? You got it!",
  price_range: 2},

  {name: "Oz Kafe", 
  url: "http://www.ozkafe.com/",
  address: "6-361 Elgin Street, Ottawa, ON, K2P 1M9",
  phone_number: "613-234-0907",
  walking_time_in_minutes: 26,
  tags: ["Eat It", "Seafood", "Italian", "International", "Gluten Free Friendly", "Vegan Friendly"],
  description: "There's no place like Oz.",
  price_range: 3},

  {name: "Bread and Sons", 
  url: "http://www.breadandsons.ca/",
  address: "195 Bank Street, Ottawa, ON,",
  phone_number: "613-230-5302",
  walking_time_in_minutes: 25,
  tags: ["Eat It", "Pizza", "Pastry", "Bakery"],
  description: "Fresh bread baked daily.",
  price_range: 1},

  {name: "Wellington Gastropub", 
  url: "http://www.thewellingtongastropub.com/",
  address: "1325 Wellington Street West, Ottawa, ON, K1y 3B2",
  phone_number: "613-729-1315",
  walking_time_in_minutes: 72,
  tags: ["Eat It", "International"],
  description: "TMenus change daily with adventurous choices.",
  price_range: 4},

  {name: "Restaurant 18", 
  url: "http://www.Eat It18.com/en/default.aspx",
  address: "18 York Street, Ottawa, ON, K1N 5T5",
  phone_number: "613-244-1188",
  walking_time_in_minutes: 6,
  tags: ["Eat It", "Steakhouse", "International", "Gluten Free"],
  description: "Try their famous raw food bar.",
  price_range: 3},

  {name: "Speakeasy", 
  #url: "http://www.Eat It18.com/en/default.aspx",
  address: "Basement of Union613, 315 Somerset Street West, Ottawa, ON, K2P 0J8",
  phone_number: "613-231-1010",
  walking_time_in_minutes: 27,
  tags: ["Eat It", "Southern Soul Food"],
  description: "An honest to goodness, modern day speakeasy... but you didn't hear it from us.",
  price_range: 3},

  {name: "Union613", 
  url: "http://union613.ca/",
  address: "315 Somerset Street West, Ottawa, ON, K2P 0J8",
  phone_number: "613-231-1010",
  walking_time_in_minutes: 27,
  tags: ["Eat It", "drink it", "Southern Soul Food"],
  description: "Communal seating and a whole lot of bourbon beverages.",
  price_range: 3},

  {name: "Slice & Co.", 
  #url: "http://union613.ca/",
  address: "399 Elgin Street, Ottawa, ON, K2P 0J8",
  phone_number: "613-627-2345",
  walking_time_in_minutes: 26,
  tags: ["Eat It", "drink it", "Pizza", "Sandwiches"],
  description: "Creative pizza toppings, and open late.",
  price_range: 3},

  {name: "Atelier", 
  url: "http://www.atelierEat It.ca/",
  address: "540 Rochester Street, Ottawa, ON, K1A 0E4",
  phone_number: "613-321-3537",
  walking_time_in_minutes: 58,
  tags: ["Eat It", "Gourmet", "International"],
  description: "Serves a 12-course tsting menu every night.",
  price_range: 4},

  {name: "Freshii", 
  url: "http://www.freshii.com/",
  address: "98 Sparks Street, Ottawa, ON, K1P 5B6",
  phone_number: "613-695-8338",
  walking_time_in_minutes: 16,
  tags: ["Eat It", "Healthy", "Vegetarian", "Soups", "Sandwiches"],
  description: "Fresh food in a flash",
  price_range: 1},

  {name: "Zen Kitchen", 
  url: "http://www.zenkitchen.ca/",
  address: "634 Somerset Street West, Ottawa, ON, K1R 5K4",
  phone_number: "613-233-6404",
  walking_time_in_minutes: 38,
  tags: ["Eat It", "Vegetarian", "International", "Patio"],
  description: "Healthy, environmentally friendly foods. Sunday night is Jazz night!",
  price_range: 3},

  {name: "Milagro", 
  url: "http://www.milagrogrill.com/",
  address: "357 Richmond Roach, Ottawa, ON, K2A 0E7",
  phone_number: "613-722-8011",
  walking_time_in_minutes: 91,
  tags: ["Eat It", "Gluten Free Friendly", "Latin American", "Mexican"],
  description: "Known for its shrimp stew and its mole sauce made of chiles... and chocolate!",
  price_range: 3},

  {name: "Lyons Tapas Bar", 
  url: "http://www.222lyontapasbar.com/",
  address: "222 Lyon Street North, Ottawa, ON, K1R 1B4",
  phone_number: "613-238-0222",
  walking_time_in_minutes: 31,
  tags: ["Eat It", "Tapas"],
  description: "You've gotta taste these tapas!",
  price_range: 3},

  {name: "Carmellos Italian Eat It and Bar", 
  url: "http://www.carmellos.ca/",
  address: "300 Sparks Street, Ottawa, ON, K1A 0H8",
  phone_number: "613-563-4349",
  walking_time_in_minutes: 24,
  tags: ["Eat It", "Italian"],
  description: "Italian on a budget.",
  price_range: 2},

  {name: "Mello's", 
  #url: "http://www.222lyontapasbar.com/",
  address: "290 Dalhousie Street, Ottawa, ON, K1N 7E5",
  phone_number: "613-241-1909",
  walking_time_in_minutes: 4,
  tags: ["Eat It", "Brunch", "International", "Diner"],
  description: "Great comfort food that kicks it up a notch for dinner!",
  price_range: 2},

  {name: "The Whalesbone", 
  url: "http://www.thewhalesbone.com/", 
  address: "430 Bank Street, Ottawa, Canada", 
  phone_number: "(613) 231-8569",
  walking_time_in_minutes: 30, 
  tags: ["eat it", "seafood"],
  description: "Best fresh seafood in town",
  price_range: 3},

  {name: "107 Fourth Avenue Wine Bar", 
  url: "http://107fourthavenue.com/",
  address: "107 Fourth Avenue, Ottawa, Canada", 
  phone_number:"613-236-0040", 
  walking_time_in_minutes: 40, 
  tags: ["eat it", "drink it", "patio", "tapas"],
  description:"Great romantic night out",
  price_range: 3},

  {name: "Anna Thai", 
  url: "http://www.urbanspoon.com/r/250/1450126/restaurant/Wellington-West/Anna-Fine-Thai-Cuisine-Ottawa", 
  address: "91 Holland Avenue, Ottawa, Ontario, Canada", 
  phone_number: "(613) 759 8472", 
  tags:["eat it", "thai"], 
  walking_time_in_minutes: 60, 
  tags: ["eat it", "thai"],
  description: "Best thai in Ottawa",
  price_range: 2},
  
  {name: "Le Boulanger Francais", 
   url: "http://www.bennysbistro.ca/bakery/", 
   address: "119 Murray Street, Ottawa, Canada", 
   phone_number: "613-789-7941", 
   walking_time_in_minutes: 10, 
   tags: ["eat it", "french", "bakery"]},

  {name: "Bread&Sons", 
   url: "http://www.breadandsons.ca/",
   address: "195 Bank St. Ottawa, Canada",
   phone_number: "613-230-5302",
   tags: ["eat it", "bakery", "pizza", "coffee"]}
]

do_it.each do |place|
  tags = place.delete(:tags)
  place = Place.new(place)
  place.tag_list.add(tags)
  place.tag_list.add("do it")
  place.save
end

drink_it.each do |place|
  tags = place.delete(:tags)
  place = Place.new(place)
  place.tag_list.add(tags)
  place.tag_list.add("drink it")
  place.save
end

eat_it.each do |place|
  tags = place.delete(:tags)
  place = Place.new(place)
  place.tag_list.add(tags)
  place.tag_list.add("eat it")
  place.save
end
